version: '3.8'
services:
  vite:
    container_name: react
    image: node:18
    volumes:
      - .:/workdir
    working_dir: /workdir
    ports:
      - 3000:3000
    command: >
      bash -c "
        npm install &&
        npm run start
      "
    tty: true
    stdin_open: true
